[tool.poetry]
name = "okama-dash"
version = "0.1.0"
description = "Python financial widgets with okama and Dash (plotly)"
authors = ["Sergey Kikevich <sergey@rostsber.ru>"]
license = "MIT"
readme = "README.md"
packages = [{include = "okama_dash"}]

[tool.poetry.dependencies]
python = ">=3.7, <4.0.0"
okama = "^1.2.2"
dash = "^2.5.1"
dash-daq = "^0.5.0"
dash-bootstrap-components = "^1.2.0"
plotly = "^5.9.0"
Flask-Caching = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
gunicorn = { version = "^20.1.0", optional = true }
black = { version = "^22.6.0", optional = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
